exp:
    project_name: base_diffusion
    run_name: base_run
    exp_dir: experiments
    device: cpu
    seed: 54
    use_wandb: True
    model_type: diffusion

data:
    input_train_dir: food_data/train
    input_val_dir: food_data/test
    drop_last: true
    shuffle: true
    train_batch_size: 32
    val_batch_size: 32
    workers: 2

train:
    trainer: base_diffusion_trainer
    model: base_diffusion
    dataset_name: base_dataset
    noise_scheduler: ddpm
    optimizer: adam
    checkpoint_path: null
    val_metrics: ["fid"]
    start_step: 0
    steps: 10
    log_step: 5
    checkpoint_step: 5
    val_step: 5


model_args:
    hidden_dim: 3
    blocks_num: 2
    num_steps: 100


ddpm_args:
    num_timesteps: 100
    beta_min: 1e-4
    beta_max: 2e-2


optimizer_args:
    lr: 0.0001

losses:
    mse: 1.0


