exp:
    project_name: base_diffusion
    run_name: dhariwal_unet
    exp_dir: experiments
    device: cuda:1
    seed: 54
    use_wandb: True
    model_type: diffusion

data:
    input_train_dir: train
    input_val_dir: test
    drop_last: true
    shuffle: true
    train_batch_size: 64
    val_batch_size: 128
    workers: 2

train:
    trainer: base_diffusion_trainer
    model: DhariwalUnet
    dataset_name: base_dataset
    noise_scheduler: ddpm
    optimizer: adam
    checkpoint_path: null
    val_metrics: ["fid"]
    start_step: 0
    gamma: 0.1
    uncond_prob: 0.1
    steps: 70000
    log_step: 100
    checkpoint_step: 2000
    val_step: 2000


model_args:
    img_resolution: 64
    in_channels: 3
    out_channels: 3
    label_dim: 102
    augment_dim: 0
    model_channels: 64
    channel_mult: [1,2,3,4]
    channel_mult_emb: 4
    num_blocks: 3
    attn_resolutions: [32,16,8]
    dropout: 0.10
    label_dropout: 0


ddpm_args:
    num_timesteps: 1000
    beta_min: 1e-4
    beta_max: 2e-2


optimizer_args:
    lr: 0.0002

losses:
    mse: 1.0


