exp:
    project_name: base_diffusion
    run_name: torch_unet
    exp_dir: experiments
    device: cuda:1
    seed: 54
    use_wandb: True
    model_type: diffusion

data:
    input_train_dir: train
    input_val_dir: test
    drop_last: true
    shuffle: true
    train_batch_size: 64
    val_batch_size: 128
    workers: 2

train:
    trainer: base_diffusion_trainer
    model: TorchUnet
    dataset_name: base_dataset
    noise_scheduler: ddpm
    optimizer: adam
    checkpoint_path: null
    val_metrics: ["fid"]
    uncond_prob: 0.1
    start_step: 0
    steps: 70000
    log_step: 100
    checkpoint_step: 2000
    val_step: 2000


model_args:
    dim: 64
    dim_mults: [1, 2, 4, 4]
    flash_attn: True
    channels: 3
    self_condition: True


ddpm_args:
    num_timesteps: 1000
    beta_min: 1e-4
    beta_max: 2e-2


optimizer_args:
    lr: 0.0002

losses:
    mse: 1.0
